In [2]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [3]:
df_jugadores = pd.read_csv("jugadores.csv")
df_jugadores

,player_id,seleccion,numero,posicion,jugador,fecha_nac,edad,caps,goles_seleccion,club,...,keeper_performance_cspct,keeper_penalty_kicks_pkatt,keeper_penalty_kicks_pka,keeper_penalty_kicks_pksv,keeper_penalty_kicks_pkm,keeper_penalty_kicks_savepct,keeper_playing_time_90s,nat3,valor_mercado_eur,posicion_tm
0,1,Czech Republic,1,GK,Matěj Kovář,2000-05-17,26,19,0,PSV Eindhoven,...,22.6,4.0,3.0,0.0,1.0,0.0,31.0,CZE,7000000.0,Goalkeeper
1,2,Czech Republic,2,DF,David Zima,2000-11-08,25,24,1,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,4500000.0,Centre-Back
2,3,Czech Republic,3,DF,Tomáš Holeš,1993-03-31,33,40,2,Slavia Prague,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,2200000.0,Centre-Back
3,4,Czech Republic,4,DF,Robin Hranáč,2000-01-29,26,13,1,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,5500000.0,Centre-Back
4,5,Czech Republic,5,DF,Vladimír Coufal,1992-08-22,33,61,2,TSG Hoffenheim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CZE,7000000.0,Right-Back
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1240,1241,Panama,22,GK,Orlando Mosquera,1994-12-25,31,47,0,Al-Fayha,...,21.9,6.0,2.0,2.0,2.0,50.0,32.0,PAN,350000.0,Goalkeeper
1241,1242,Panama,23,DF,Michael Amir Murillo,1996-02-11,30,93,9,Beşiktaş,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAN,7000000.0,Right-Back
1242,1243,Panama,24,FW,Azarias Londoño,2001-06-21,24,10,0,Universidad Católica,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAN,175000.0,Centre-Forward
1243,1244,Panama,25,DF,Roderick Miller,1992-04-03,34,50,2,Turan Tovuz,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175000.0,Centre-Back
1244,1245,Panama,26,DF,Jorge Gutiérrez,1998-09-01,27,18,0,Deportivo La Guaira,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325000.0,Left-Back

# Ejercicio 1 : Limpieza y Procesamiento de Datos

In [4]:
# Quiero verificar si mis datos contienen duplicados y celdas nulas
# Filas
df_jugadores.duplicated().value_counts()

False    1245
Name: count, dtype: int64

In [21]:
df_jugadores.T.duplicated()
df_jugadores.T[df_jugadores.T.duplicated() == True]

,0,1,2,3,4,5,6,7,8,9,...,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244
misc_performance_pkcon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nat3,CZE,CZE,CZE,CZE,CZE,CZE,CZE,CZE,CZE,CZE,...,PAN,PAN,NaN,PAN,PAN,PAN,PAN,PAN,NaN,NaN

#### 2.a 
Contar cuántos jugadores tenemos por selección. ¿Hay la misma cantidad de jugadores para todas las selecciones? ¿Cuáles son las selecciones con menos jugadores convocados?

In [32]:
df_jugadores_por_seleccion = df_jugadores["seleccion"].value_counts().reset_index()
df_jugadores_por_seleccion.columns = ['seleccion', 'cant_jugadores']
df_jugadores_por_seleccion

                 seleccion  cant_jugadores
0           Czech Republic              26
1                   Mexico              26
2             South Africa              26
3              South Korea              26
4   Bosnia and Herzegovina              26
5                    Qatar              26
6              Switzerland              26
7                   Brazil              26
8                Australia              26
9                    Haiti              26
10                 Morocco              26
11                Scotland              26
12                  Turkey              26
13                Paraguay              26
14           United States              26
15                 Curacao              26
16                  France              26
17                 Ecuador              26
18                 Germany              26
19             Ivory Coast              26
20                   Japan              26
21             Netherlands              26
22                  Sweden              26
23                 Tunisia              26
24                 Belgium              26
25                   Egypt              26
26                    Iran              26
27             New Zealand              26
28              Cape Verde              26
29            Saudi Arabia              26
30                   Spain              26
31                 Uruguay              26
32                 Croatia              26
33                    Iraq              26
34                  Norway              26
35                 Senegal              26
36                 Algeria              26
37               Argentina              26
38                DR Congo              26
39                Colombia              26
40                   Ghana              26
41                 England              26
42                Portugal              26
43              Uzbekistan              26
44                  Panama              26
45                  Canada              25
46                  Jordan              25
47                 Austria              25

In [31]:
df_jugadores_por_seleccion[df_jugadores_por_seleccion["cant_jugadores"] < 26]

   seleccion  cant_jugadores
45    Canada              25
46    Jordan              25
47   Austria              25

La mayoría de los países tiene 26 jugadores en su selección, a excepción de Canada, Jordan y Austria que tienen exactamente 25.

#### 2.b

In [35]:
df_jugadores_por_clubes = df_jugadores["club"].value_counts().reset_index()
df_jugadores_por_clubes.columns = ["club", "cant_jugadores"]
df_jugadores_por_clubes

                      club  cant_jugadores
0          Manchester City              19
1            Bayern Munich              18
2      Paris Saint-Germain              16
3                  Arsenal              16
4                Barcelona              15
..                     ...             ...
444            Montpellier               1
445              Atromitos               1
446  St Patrick's Athletic               1
447          Hearts of Oak               1
448    Deportivo La Guaira               1

[449 rows x 2 columns]

In [39]:
df_jugadores_por_clubes[df_jugadores_por_clubes["cant_jugadores"] > 9].info

<bound method DataFrame.info of                    club  cant_jugadores
0       Manchester City              19
1         Bayern Munich              18
2   Paris Saint-Germain              16
3               Arsenal              16
4             Barcelona              15
5       Atlético Madrid              12
6              Al-Hilal              12
7     Manchester United              12
8        Crystal Palace              12
9           Galatasaray              11
10            Liverpool              11
11    Borussia Dortmund              11
12                Milan              10
13        PSV Eindhoven              10
14          Real Madrid              10
15           Fenerbahçe              10
16        Slavia Prague              10>

#### 2.c

In [ ]:
def rangos_etarios(edad):
    if edad < 24:
        return "A"
    elif 24 <= edad <= 30:
        return "B"
    else:
        return "C"

df_jugadores["rango_etario"] = df_jugadores["edad"].apply(rangos_etarios

'A'